language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '11'

jobs:
  include:
    - stage: test
      script: npm run test:prod
    - stage: build & deploy
      if: branch = master
      script: npm run build && npm run semantic-release
