name: Publish to NPM

on: [push]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - run: yarn test

      - run: yarn build
